# Fly.io deployment configuration
# https://fly.io

app = "badminton-wind-bot"
primary_region = "sin"  # Singapore - change to closest: iad (US East), lhr (London), sin (Singapore)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHON_VERSION = "3.10"

[processes]
  app = "python -m src.integrations.telegram_bot"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
