name: CI

# Temporarily disabled - focusing on bot deployment
on:
  workflow_dispatch:  # Manual trigger only
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate sample data
      run: |
        python scripts/make_sample_data.py
    
    - name: Run tests
      run: |
        pytest -v -m "not slow"
    
    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term
  
  smoke_train:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate sample data
      run: |
        python scripts/make_sample_data.py
    
    - name: Smoke test training
      run: |
        # Train baseline
        python -m src.cli.train --model baseline
        
        # Quick LSTM training (1 epoch)
        python -m src.cli.train --model lstm --epochs 1
        
        # Test inference
        python -m src.cli.infer --model experiments/latest/model.h5
